### ISSUE TITLE
Inspiration sammeln

### ISSUE THREAD

**Issue by lukas-h** [hansomatig/kunst-am-kirchberg#13]
- Interessante Design-Elemente von anderen Websites z.B. von Museen sammeln

**Comment by hansomatig** [comment]
https://www.kunsthaus-artes.de/artes-berlin/?expa=GO&gclid=Cj0KCQjw24qHBhCnARIsAPbdtlL7DPLUjWqeiguSAvZHwED6Z4QRe0RKSuxg9pja-HEith8wfEa-UOIaAj5bEALw_wcB

**Comment by hansomatig** [comment]
https://pashminart-museum.com/?gclid=Cj0KCQjw24qHBhCnARIsAPbdtlKBGcjSyR7EL5qRIKTlfRLb6G8tWTx0t5fcDId0Cf36Iy0I7NJZWxgaAtbhEALw_wcB

**Comment by hansomatig** [comment]
https://pashminart-museum.com/?gclid=Cj0KCQjw24qHBhCnARIsAPbdtlKBGcjSyR7EL5qRIKTlfRLb6G8tWTx0t5fcDId0Cf36Iy0I7NJZWxgaAtbhEALw_wcB

**Comment by hansomatig** [comment]
> https://pashminart-museum.com/?gclid=Cj0KCQjw24qHBhCnARIsAPbdtlKBGcjSyR7EL5qRIKTlfRLb6G8tWTx0t5fcDId0Cf36Iy0I7NJZWxgaAtbhEALw_wcB

Berliner Kunstmuseum

**Comment by hansomatig** [comment]
https://muenchner-galerien.de/
