### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by hansomatig** [hansomatig/kunst-am-kirchberg#22]
Die Navbar an die Seite verschieben

**Comment by lukas-h** [comment]
<img width="279" alt="Screenshot 2021-09-28 at 19 18 24" src="https://user-images.githubusercontent.com/10634693/135135825-2eb9daae-0a03-4365-8702-e1aafebc9797.png">

**Comment by lukas-h** [comment]
Mobiloptimierung:

- [ ] @media queries / breakpoints (z.B. max-width: 799px)
- [ ] flex-wrap: nowrap
- [ ] overflow-(x oder y): scroll

<img width="384" alt="Screenshot 2021-09-28 at 20 06 38" src="https://user-images.githubusercontent.com/10634693/135141667-439608ad-559f-487a-93a0-0c6566f34dd8.png">
